[package]
name = "amb_file_seacher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
regex = "1.4"
colored = "^2.0.0"
termcolor = "1.1"